### ISSUE TITLE
Plaetje draaien kan niet tegen haakjes () in bestandsnaam.

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#439]
```
Uncaught CsrDelft\common\CsrException: Thumb maken mislukt: /app/data/foto/fotoalbum/Publiek/%2851 of 323%29.jpg in /app/lib/model/entity/fotoalbum/Foto.class.php:145
Stack trace:
#0 /app/lib/model/fotoalbum/FotoModel.php(77): CsrDelft\model\entity\fotoalbum\Foto->createThumb()
#1 /app/lib/model/fotoalbum/FotoModel.php(51): CsrDelft\model\fotoalbum\FotoModel->verwerkFoto(Object(CsrDelft\model\entity\fotoalbum\Foto))
#2 /app/lib/model/entity/fotoalbum/Foto.class.php(186): CsrDelft\model\fotoalbum\FotoModel->retrieveAttributes(Object(CsrDelft\model\entity\fotoalbum\Foto), Array)
#3 /app/lib/controller/FotoAlbumController.class.php(332): CsrDelft\model\entity\fotoalbum\Foto->rotate(90)
#4 [internal function]: CsrDelft\controller\FotoAlbumController->roteren(Object(CsrDelft\model\entity\fotoalbum\FotoAlbum))
#5 /app/lib/controller/framework/Controller.abstract.php(205): call_user_func_array(Array, 
```

**Comment by mathcals** [comment]
Fixed in 38a7
