### ISSUE TITLE
Geen 404 in mededelingen

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#66]
Voor Url https://csrdelft.nl/mededelingen/177/

**Comment by qurben** [comment]
Gevonden door Google bot, Majestic12 bot, Megaindex en WiseGuys

**Comment by qurben** [comment]
Fix: Doe een propere 404

**Comment by brussee** [comment]
```
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-10, 10' at line 1' in /srv/www/csrdelft.nl/lib/model/framework/Database.singleton.php:152 Stack trace: 
#0 /srv/www/csrdelft.nl/lib/model/framework/Database.singleton.php(152): PDOStatement->execute(Array) 
#1 /srv/www/csrdelft.nl/lib/model/framework/PersistenceModel.abstract.php(85): Database::sqlSelect(Array, 'mededelingen', '((vervaltijd IS...', Array, NULL, 'datum DESC', 10, -10) 
#2 /srv/www/csrdelft.nl/lib/model/mededelingen/MededelingenModel.class.php(153): PersistenceModel->find('((vervaltijd IS...', Array, NULL, 'datum DESC', 10, -10) 
#3 /srv/www/csrdelft.nl/lib/view/MededelingenView.class.php(149): MededelingenModel->getLijstVanPagina('', 10, false) 
#4 /srv/www/csrdelft.nl/data/smarty/compiled/e37aaa1a401a90df82e75192680ff3410ecd1003_0.file.pagina.tpl.php(74): MededelingenView->view() 
#5 /srv/www/csrdelft.nl/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(122): content_57641f8b9d3ee7_31673286(Object(Smarty_Internal_Template)) 
#6 /srv/www/csrdelft.nl/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(199): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) 
#7 /srv/www/csrdelft.nl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(159): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) 
#8 /srv/www/csrdelft.nl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(191): Smarty_Internal_Template->render(false, 1) 
#9 /srv/www/csrdelft.nl/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(109): Smarty_Internal_TemplateBase->_execute('layout/pagina.t...', NULL, NULL, NULL, 1) 
#10 /srv/www/csrdelft.nl/lib/view/CsrLayoutPage.class.php(81): Smarty_Internal_TemplateBase->display('layout/pagina.t...') 
#11 /srv/www/csrdelft.nl/htdocs/index.php(63): CsrLayoutPage->view() 
#12 {main}
```

**Comment by brussee** [comment]
^ Oftewel het is een paging error: LIMIT -10,10 mag niet van MySQL.

**Comment by brussee** [comment]
Kijk naar hoe het in ForumPostsModel is gedaan met de Paging interface. https://github.com/csrdelft/csrdelft.nl/blob/dac8230abea34cbcebfff0f36c64b63b2190dd06/lib/model/ForumModel.class.php#L916

**Comment by qurben** [comment]
Deze error doet zich alleen voor bij mededelingen die niet bestaan.

**Comment by brussee** [comment]
https://www.dropbox.com/s/v8e31n3l83jv7rc/mededelingen177.PNG

**Comment by brussee** [comment]
Ik zie dat MededelingenView.class.php op regel 149 iets uit het model haalt: MededelingenModel->getLijstVanPagina('', 10, false)
Dit is helemaal goed wat betreft MVC, alleen is het nog beter om de Controller alle acties (dus ook GET) op het Model te laten uitvoeren (dat is ook MVC) want daardoor kun je met de Controller de toegang tot het Model controleren (dat moet eigenlijk) en het debuggen zoals nu wordt makkelijker, want dan kan je bijvoorbeeld deze bug traceren tot en met de Controller actie en query parameters van het request.

**Comment by brussee** [comment]
In de view():
```
if (!$this->paginaNummerOpgevraagd) {
	$this->paginaNummer = $this->model->getPaginaNummer($this->geselecteerdeMededeling, $this->prullenbak);
}
...
$this->smarty->assign('lijst', $this->model->getLijstVanPagina($this->paginaNummer, LidInstellingen::get('mededelingen', 'aantalPerPagina'), $this->prullenbak));
```

In de constructor:
```
if ($paginanummer !== null) {
	$this->paginaNummer = $paginanummer;
	$this->paginaNummerOpgevraagd = true;
} else {
	$this->paginaNummer = 1;
}
```

En in de controller:
```
    public function bekijken($id = 0, $pagina = 1) {
        return new MededelingenView($id, $pagina, $this->prullenbak);
    }
```

Dus het komt omdat het request mededelingen/177 (default actie bekijken) een lege string als pagina parameter zet.

**Comment by brussee** [comment]
^ opgelost in #72
